# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rubbish.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1063, 745)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 130, 1031, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_img = QtWidgets.QLabel(self.frame)
        self.label_img.setGeometry(QtCore.QRect(30, 40, 471, 521))
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setText("")
        self.label_img.setTextFormat(QtCore.Qt.AutoText)
        self.label_img.setScaledContents(False)
        self.label_img.setWordWrap(False)
        self.label_img.setObjectName("label_img")
        self.pushButton_load = QtWidgets.QPushButton(self.frame)
        self.pushButton_load.setGeometry(QtCore.QRect(570, 440, 121, 41))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_shibie = QtWidgets.QPushButton(self.frame)
        self.pushButton_shibie.setGeometry(QtCore.QRect(850, 440, 121, 41))
        self.pushButton_shibie.setObjectName("pushButton_shibie")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(570, 0, 81, 51))
        self.label_2.setObjectName("label_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(570, 40, 401, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 81, 51))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(570, 500, 401, 61))
        self.textEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 40, 621, 101))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.pushButton_load.clicked.connect(Dialog.load_image) # type: ignore
        self.pushButton_shibie.clicked.connect(Dialog.shibie) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "垃圾分类"))
        self.pushButton_load.setText(_translate("Dialog", "上传图片"))
        self.pushButton_shibie.setText(_translate("Dialog", "开始识别"))
        self.label_2.setText(_translate("Dialog", "识别结果："))
        self.label_3.setText(_translate("Dialog", "图片显示："))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件位置:</p></body></html>"))
        self.label.setText(_translate("Dialog", "6大垃圾分类器"))
